### ISSUE TITLE
Cmake fails to work on Marconi

### ISSUE THREAD

**Issue by DenSto** [stellaGK/stella#53]
After merging the 'external git_version' pull request, cmake fails on Marconi with these messages:

/marconi/home/userexternal/dstonge0/Codes/stella/externals/git_version/src/git_version_impl.F90(14): error #6337: This is not a valid lvalue or rvalue.   [GIT_VERSION]
    length = min(max_length, len(GIT_VERSION))
---------------------------------^

Apparently the macros aren't being resolved correctly.

**Comment by ZedThree** [comment]
What compiler are you using? Could you paste your compile line please?

**Comment by DenSto** [comment]
I'm using the intel compilers.  BTW, for some reason `cmake . -B build --verbose` doesn't work for me.

**Comment by ZedThree** [comment]
Sorry, I typed that in a hurry, I meant `cmake --build build --verbose`, where I've assumed you're running from `stella`, and you have a build directory `stella/build`.

This looks to be because the system `git` on Marconi is pretty old. If you load the `git` module you should get 2.17 which will work. I think I should also be able to make the `fortran-git-version` library work with older git versions too.
