### PR TITLE
Bump fortran-git-version submodule to fix issue with older git

### LINKED ISSUE #53: Cmake fails to work on Marconi
After merging the 'external git_version' pull request, cmake fails on Marconi with these messages:

/marconi/home/userexternal/dstonge0/Codes/stella/externals/git_version/src/git_version_impl.F90(14): error #6337: This is not a valid lvalue or rvalue.   [GIT_VERSION]
    length = min(max_length, len(GIT_VERSION))
---------------------------------^

Apparently the macros aren't being resolved correctly.

### PR DESCRIPTION
**Pull request by ZedThree**
Fixes #53 

@DenSto This fixes things for me on a different system when I use the system git, but you probably want to check for yourself on Marconi!

### CODE REVIEW

**Comment by DenSto** [comment]
Works for me now. Pulling into master
